version: '2.1'
services:
  server:
  
    image: cassandra:latest
    container_name: cassandra_server
    ports:
     - "9042:9042"     
    restart: always
    networks:
      - target-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60      

  cassandra-load-keyspace:
      container_name: cassandra_load_keyspace
      image: cassandra:latest
      networks:
        - target-network      
      depends_on:
        server:
          condition: service_healthy
      volumes:
        - ./schema.cql:/opt/cassandra/schema.cql
      command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra_server -f /opt/cassandra/schema.cql"

networks:
  target-network:
    driver: bridge
    ipam:
      driver: default